import { useMemo, useState } from "react";
import { getPrestigeLevel } from "../legacy/legacyEngine.js";
import { SwipeTabs } from "./SwipeNavigation.jsx";

const gold="#c9a84c",panel="#161a24",muted="#73798d";
const money=value=>`€${Math.abs(value??0)>=1000?`${((value??0)/1000).toFixed(1)}M`:`${Math.round(value??0)}K`}`;
const seasonLabel=value=>`${value}/${String(Number(value)+1).slice(-2)}`;
const recordCards=[
  ["appearances","PARTIDOS","👕"],["goals","GOLES","⚽"],["assists","ASISTENCIAS","🎯"],["cleanSheets","PORTERÍAS A CERO","🧤"],
];

function SectionTitle({children}){return <div style={{fontSize:10,color:muted,fontWeight:900,letterSpacing:".9px",margin:"18px 0 9px"}}>{children}</div>}
function Stat({label,value,accent=gold}){return <div style={{background:panel,border:"1px solid rgba(255,255,255,.06)",borderRadius:10,padding:11,textAlign:"center"}}><div style={{fontSize:19,color:accent,fontWeight:900}}>{value}</div><div style={{fontSize:8,color:muted,marginTop:4,fontWeight:800}}>{label}</div></div>}
function Empty({children}){return <div style={{background:panel,border:"1px solid rgba(255,255,255,.06)",borderRadius:12,padding:28,textAlign:"center",color:muted,fontSize:11,lineHeight:1.6}}>{children}</div>}
function PlayerLine({player,value,label}){return <div style={{display:"flex",alignItems:"center",gap:10,background:panel,borderRadius:9,padding:10}}><div style={{width:32,height:32,borderRadius:9,display:"grid",placeItems:"center",background:"rgba(201,168,76,.12)",color:gold,fontSize:11,fontWeight:900}}>{player?.pos??"—"}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,color:"#eef0f6",fontWeight:800,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{player?.name??"Sin datos"}</div><div style={{fontSize:9,color:muted,marginTop:2}}>{label}</div></div><div style={{fontSize:17,color:gold,fontWeight:900}}>{value}</div></div>}

function Overview({archive,legacy,team}){
  const seasons=archive.seasons??[];const records=Object.values(archive.playerRecords??{});
  const totals=seasons.reduce((sum,item)=>({matches:sum.matches+(item.results?.fixtures?.length??0),wins:sum.wins+(item.results?.wins??0),goals:sum.goals+(item.goalsFor??0)}),{matches:0,wins:0,goals:0});
  const level=getPrestigeLevel(legacy.clubPrestige);
  return <>
    <div style={{background:"radial-gradient(circle at 80% 0%,rgba(201,168,76,.28),transparent 42%),linear-gradient(145deg,#1b1b1b,#0e1016)",border:"1px solid rgba(201,168,76,.3)",borderRadius:16,padding:18,boxShadow:"0 12px 35px rgba(0,0,0,.25)"}}><div style={{fontSize:9,color:gold,fontWeight:900,letterSpacing:"1.5px"}}>ARCHIVO HISTÓRICO</div><div style={{fontSize:24,color:"#fff",fontWeight:950,marginTop:5}}>{team?.name}</div><div style={{fontSize:11,color:level.color,marginTop:5}}>{level.label} · Prestigio {Math.round(legacy.clubPrestige)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:17}}><Stat label="TEMPORADAS" value={seasons.length}/><Stat label="TÍTULOS" value={legacy.trophies.length}/><Stat label="JUGADORES" value={records.length}/></div></div>
    <SectionTitle>LEGADO GLOBAL</SectionTitle><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}><Stat label="PARTIDOS" value={totals.matches}/><Stat label="VICTORIAS" value={totals.wins} accent="#22c55e"/><Stat label="GOLES" value={totals.goals} accent="#60a5fa"/></div>
    <SectionTitle>HITOS</SectionTitle>{archive.milestones?.length?<div style={{display:"flex",flexDirection:"column",gap:7}}>{archive.milestones.slice(0,6).map(item=><div key={item.id} style={{background:panel,borderLeft:`3px solid ${gold}`,borderRadius:9,padding:11,display:"flex",gap:10}}><div style={{fontSize:22}}>{item.icon}</div><div><div style={{fontSize:11,color:"#eef0f6",fontWeight:800}}>{item.title}</div><div style={{fontSize:9,color:muted,marginTop:3}}>{seasonLabel(item.season)} · {item.summary}</div></div></div>)}</div>:<Empty>Los grandes hitos aparecerán al cerrar temporadas, conquistar títulos y romper récords.</Empty>}
  </>;
}

function Seasons({archive,teams}){
  const seasons=archive.seasons??[];const [selectedId,setSelectedId]=useState(seasons[0]?.id??null);const selected=seasons.find(item=>item.id===selectedId)??seasons[0];
  const teamName=id=>teams.find(team=>team.id===id)?.name??id;
  if(!selected)return <Empty>Tu primera temporada completa inaugurará el archivo histórico.</Empty>;
  return <><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:7}}>{seasons.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} style={{flex:"0 0 auto",background:selected.id===item.id?"rgba(201,168,76,.17)":panel,border:`1px solid ${selected.id===item.id?gold:"rgba(255,255,255,.07)"}`,borderRadius:10,padding:"9px 13px",color:selected.id===item.id?gold:"#9aa0b4",fontSize:10,fontWeight:800}}>{seasonLabel(item.season)}</button>)}</div>
    <div style={{background:"linear-gradient(135deg,rgba(201,168,76,.16),#161a24)",border:"1px solid rgba(201,168,76,.22)",borderRadius:13,padding:14,marginTop:7}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontSize:10,color:muted}}>TEMPORADA {seasonLabel(selected.season)}</div><div style={{fontSize:21,color:"#fff",fontWeight:900,marginTop:3}}>{selected.position}.ª posición</div></div>{selected.title&&<div style={{fontSize:25}}>🏆</div>}</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6,marginTop:14}}><Stat label="PTS" value={selected.points}/><Stat label="GF" value={selected.goalsFor}/><Stat label="GC" value={selected.goalsAgainst}/><Stat label="PREST." value={`${selected.prestigeDelta>0?"+":""}${selected.prestigeDelta??0}`}/></div></div>
    {!selected.migrated&&<><SectionTitle>PROTAGONISTAS</SectionTitle><div style={{display:"flex",flexDirection:"column",gap:7}}><PlayerLine player={selected.topScorer} value={selected.topScorer?.goals??0} label="Máximo goleador"/><PlayerLine player={selected.topAssister} value={selected.topAssister?.assists??0} label="Máximo asistente"/><PlayerLine player={selected.playerOfYear} value={selected.playerOfYear?.averageRating||"—"} label="Jugador de la temporada"/></div>
    <SectionTitle>BALANCE DE GESTIÓN</SectionTitle><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}><Stat label="VALOR PLANTILLA" value={money(selected.squadValue)}/><Stat label="BALANCE" value={money(selected.finances?.balance)} accent={(selected.finances?.balance??0)>=0?"#22c55e":"#ef4444"}/><Stat label="CANTERANOS" value={selected.promotedYouth??0}/><Stat label="MEJOR FICHAJE" value={selected.bestSigning?.name?.split(" ").slice(-1)[0]??"—"}/></div>
    <SectionTitle>CLASIFICACIÓN FINAL</SectionTitle><div style={{background:panel,borderRadius:11,overflow:"hidden"}}>{selected.standings?.map(row=><div key={row.teamId} style={{display:"grid",gridTemplateColumns:"25px 1fr 30px 32px",gap:6,padding:"8px 10px",borderBottom:"1px solid rgba(255,255,255,.05)",fontSize:10,color:row.teamId===selected.clubId?gold:"#9aa0b4",fontWeight:row.teamId===selected.clubId?900:500}}><span>{row.position}</span><span>{teamName(row.teamId)}</span><span>{row.goalDifference>0?"+":""}{row.goalDifference}</span><strong>{row.points}</strong></div>)}</div></>}
    {selected.migrated&&<Empty>Esta temporada procede de una partida anterior. Conservamos posición, puntos y prestigio; los detalles avanzados empezarán a registrarse en el próximo cierre.</Empty>}</>;
}

function Trophies({legacy}){return legacy.trophies.length?<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{legacy.trophies.map(trophy=><div key={trophy.id} style={{background:"radial-gradient(circle at 50% 20%,rgba(201,168,76,.25),transparent 35%),#161a24",border:"1px solid rgba(201,168,76,.28)",borderRadius:14,padding:17,textAlign:"center"}}><div style={{fontSize:43,filter:"drop-shadow(0 5px 8px rgba(201,168,76,.25))"}}>{trophy.icon||"🏆"}</div><div style={{fontSize:12,color:"#fff",fontWeight:900,marginTop:8}}>{trophy.name}</div><div style={{fontSize:9,color:gold,marginTop:4}}>{seasonLabel(trophy.season)}</div><div style={{fontSize:8,color:muted,marginTop:7}}>{trophy.clubName}<br/>{trophy.managerName}</div></div>)}</div>:<Empty>Las vitrinas esperan el primer título de tu era.</Empty>}

function Records({archive}){
  const players=Object.values(archive.playerRecords??{});const seasons=(archive.seasons??[]).filter(item=>!item.migrated);
  if(!players.length&&!seasons.length)return <Empty>Los récords se consolidarán al completar una temporada.</Empty>;
  const bestSeason=[...seasons].sort((a,b)=>a.position-b.position||b.points-a.points)[0];
  const biggestSigning=[...seasons].filter(item=>item.bestSigning).sort((a,b)=>(b.bestSigning.cost??0)-(a.bestSigning.cost??0))[0]?.bestSigning;
  const biggestSale=[...seasons].filter(item=>item.biggestSale).sort((a,b)=>(b.biggestSale.value??0)-(a.biggestSale.value??0))[0]?.biggestSale;
  const maxValue=[...seasons].sort((a,b)=>(b.squadValue??0)-(a.squadValue??0))[0];
  return <><SectionTitle>RÉCORDS DEL CLUB</SectionTitle><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginBottom:17}}><Stat label="MEJOR TEMPORADA" value={bestSeason?`${bestSeason.position}.º · ${bestSeason.points} pts`:"—"}/><Stat label="VALOR MÁXIMO" value={maxValue?money(maxValue.squadValue):"—"}/><Stat label="MAYOR FICHAJE" value={biggestSigning?money(biggestSigning.cost):"—"}/><Stat label="MAYOR VENTA" value={biggestSale?money(biggestSale.value):"—"}/></div><SectionTitle>RÉCORDS INDIVIDUALES</SectionTitle>{recordCards.map(([key,label,icon])=>{const leader=[...players].sort((a,b)=>(b[key]??0)-(a[key]??0))[0];return <div key={key} style={{marginBottom:8}}><PlayerLine player={leader} value={leader?.[key]??0} label={`${icon} Récord histórico de ${label.toLowerCase()}`}/></div>})}</>;
}

function Legends({archive}){
  const legends=useMemo(()=>Object.values(archive.playerRecords??{}).sort((a,b)=>(b.legacyScore??0)-(a.legacyScore??0)),[archive.playerRecords]);
  const xi=useMemo(()=>{const take=(group,count)=>legends.filter(item=>(item.group??item.pos)===group).slice(0,count);return[...take("POR",1),...take("DEF",4),...take("MED",3),...take("DEL",3)];},[legends]);
  if(!legends.length)return <Empty>Las leyendas necesitan tiempo. Rendimiento, continuidad y títulos decidirán quién entra aquí.</Empty>;
  return <><SectionTitle>ONCE HISTÓRICO</SectionTitle><div style={{background:"linear-gradient(180deg,#163a2b,#10271e)",border:"1px solid rgba(34,197,94,.2)",borderRadius:14,padding:13,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{xi.map((player,index)=><div key={player.id} style={{gridColumn:player.group==="POR"&&index===0?"2":"auto",background:"rgba(8,15,12,.72)",borderRadius:8,padding:8,textAlign:"center"}}><div style={{fontSize:9,color:gold,fontWeight:900}}>{player.pos}</div><div style={{fontSize:9,color:"#fff",fontWeight:800,marginTop:3,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{player.name}</div></div>)}</div><SectionTitle>LEYENDAS DEL CLUB</SectionTitle><div style={{display:"flex",flexDirection:"column",gap:7}}>{legends.slice(0,10).map((player,index)=><PlayerLine key={player.id} player={player} value={`#${index+1}`} label={`${player.appearances} partidos · ${player.goals} goles · ${player.titles} títulos${player.academy?" · Cantera":""}`}/>)}</div></>;
}

function Manager({legacy,archive}){
  const manager=legacy.manager;const history=manager.history??[];const points=[...(archive.prestigeHistory??[])].reverse();
  const max=Math.max(100,...points.map(item=>item.managerPrestige??0));
  const path=points.map((item,index)=>`${points.length===1?50:index/(points.length-1)*100},${100-(item.managerPrestige??0)/max*100}`).join(" ");
  return <><div style={{background:"linear-gradient(135deg,rgba(167,139,250,.17),#161a24)",border:"1px solid rgba(167,139,250,.25)",borderRadius:14,padding:16}}><div style={{fontSize:9,color:"#a78bfa",fontWeight:900}}>CARRERA DEL ENTRENADOR</div><div style={{fontSize:22,color:"#fff",fontWeight:900,marginTop:5}}>{manager.name}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:14}}><Stat label="TEMPORADAS" value={manager.seasons}/><Stat label="VICTORIAS" value={manager.wins}/><Stat label="TÍTULOS" value={manager.titles}/></div></div>
    <SectionTitle>EVOLUCIÓN DEL PRESTIGIO</SectionTitle>{points.length?<div style={{background:panel,borderRadius:12,padding:13}}><svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{width:"100%",height:105,overflow:"visible"}}><defs><linearGradient id="legacyFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={gold} stopOpacity=".35"/><stop offset="1" stopColor={gold} stopOpacity="0"/></linearGradient></defs><polyline points={`0,100 ${path} 100,100`} fill="url(#legacyFill)"/><polyline points={path} fill="none" stroke={gold} strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div style={{display:"flex",justifyContent:"space-between",fontSize:8,color:muted}}>{points.map(item=><span key={item.season}>{item.season}</span>)}</div></div>:<Empty>La curva de prestigio comenzará al cerrar la primera temporada.</Empty>}
    <SectionTitle>TRAYECTORIA</SectionTitle>{history.length?<div style={{display:"flex",flexDirection:"column",gap:7}}>{history.map(item=><div key={`${item.season}-${item.clubId}`} style={{background:panel,borderRadius:9,padding:11,display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:11,color:"#fff",fontWeight:800}}>{item.clubName}</div><div style={{fontSize:9,color:muted,marginTop:3}}>{seasonLabel(item.season)}</div></div><div style={{textAlign:"right",fontSize:11,color:item.position===1?gold:"#9aa0b4",fontWeight:900}}>{item.position}.º{item.title&&<div style={{fontSize:9}}>🏆 {item.title}</div>}</div></div>)}</div>:<Empty>La trayectoria se escribirá temporada a temporada.</Empty>}</>;
}

export default function LegacyMuseumScreen({game,team,teams=[]}){
  const [tab,setTab]=useState("overview");const legacy=game.legacy;const archive=legacy.archive??{seasons:[],playerRecords:{},milestones:[],prestigeHistory:[]};
  const tabs=[["overview","Museo"],["seasons","Temporadas"],["trophies","Trofeos"],["records","Récords"],["legends","Leyendas"],["manager","Mánager"]];
  return <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden",background:"linear-gradient(180deg,#0e1015,#0b0c10)"}}><div style={{display:"flex",overflowX:"auto",background:"#12151d",borderBottom:"1px solid rgba(255,255,255,.06)"}}>{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{flex:"0 0 auto",minWidth:85,background:"transparent",border:"none",borderBottom:tab===id?`2px solid ${gold}`:"2px solid transparent",color:tab===id?gold:muted,padding:"11px 9px",fontSize:10,fontWeight:800}}>{label}</button>)}</div><SwipeTabs tabs={tabs.map(item=>item[0])} activeTab={tab} onChange={setTab} style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}} contentStyle={{flex:1,overflow:"hidden"}}><div style={{height:"100%",overflowY:"auto",padding:14}}>{tab==="overview"&&<Overview archive={archive} legacy={legacy} team={team}/>} {tab==="seasons"&&<Seasons archive={archive} teams={teams}/>} {tab==="trophies"&&<Trophies legacy={legacy}/>} {tab==="records"&&<Records archive={archive}/>} {tab==="legends"&&<Legends archive={archive}/>} {tab==="manager"&&<Manager legacy={legacy} archive={archive}/>}</div></SwipeTabs></div>;
}
