import { MORE_SECTIONS } from "../navigation/navigationConfig.js";
import { buildStaffRecommendations } from "../staff/staffEngine.js";

export default function MoreMenuScreen({ onNavigate, game, attentionCount = 0 }) {
  const groups=[...new Set(MORE_SECTIONS.map(item=>item.group))];
  const alerts={ attention:attentionCount, medical:game.players.filter(player=>player.injured).length, youth:game.youth?.players?.length??0, staff:buildStaffRecommendations(game).filter(item=>item.priority!=="info").length, career:(game.coachCareer?.notifications??[]).length, fans:((game.fanbase?.support??65)<42||(game.fanbase?.coachSupport??65)<42)?1:0 };
  return <div className="more-menu-enter" style={{flex:1,overflowY:"auto",padding:"16px 14px 24px"}}>
    <div style={{background:"linear-gradient(135deg,rgba(201,168,76,.14),#161a24)",border:"1px solid rgba(201,168,76,.22)",borderRadius:13,padding:15,marginBottom:18}}><div style={{fontSize:10,color:"#c9a84c",fontWeight:800,letterSpacing:".8px"}}>LEGACY MANAGER</div><div style={{fontSize:19,color:"#fff",fontWeight:800,marginTop:5}}>Centro de gestión</div><div style={{fontSize:11,color:"#6b7280",lineHeight:1.5,marginTop:4}}>Todas las áreas del club, organizadas para llegar en un solo toque.</div></div>
    {groups.map(group=><section key={group} style={{marginBottom:18}}><div style={{fontSize:9,color:"#4b5563",fontWeight:800,letterSpacing:".8px",margin:"0 2px 8px"}}>{group.toUpperCase()}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>{MORE_SECTIONS.filter(item=>item.group===group).map((item,index)=><button key={item.id} onClick={()=>onNavigate(item.id)} className="nav-tile" style={{position:"relative",minHeight:104,textAlign:"left",background:`linear-gradient(145deg,${item.accent}13,#161a24 60%)`,border:`1px solid ${item.accent}28`,borderRadius:12,padding:12,cursor:"pointer",animationDelay:`${index*35}ms`}}><div style={{width:36,height:36,borderRadius:9,background:`${item.accent}18`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,marginBottom:9}}>{item.icon}</div><div style={{fontSize:12,color:"#e8eaf0",fontWeight:800}}>{item.label}</div><div style={{fontSize:9,color:"#6b7280",lineHeight:1.35,marginTop:3}}>{item.description}</div>{alerts[item.id]>0&&<div style={{position:"absolute",top:9,right:9,minWidth:19,height:19,padding:"0 5px",borderRadius:10,background:item.id==="attention"?"#c9a84c":item.id==="medical"?"#ef4444":"#22c55e",color:item.id==="attention"?"#1a1200":"#fff",fontSize:9,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center"}}>{alerts[item.id]}</div>}</button>)}</div></section>)}
  </div>;
}
