import { useMemo, useState } from "react";
import { getKeyAttributes, getMarketValue, getPlayerSeasonStats, getPlayerTags, getPotential, getRecentForm } from "../players/playerProfile.js";
import { calculateInjuryRisk, formatMedicalDuration, getAccumulatedLoad, getLoadLevel, getPhysicalStatus, getRiskLevel } from "../medical/medicalEngine.js";
import { ATTRIBUTE_LABELS } from "../training/trainingEngine.js";
import { SwipeTabs } from "./SwipeNavigation.jsx";
import { CONTRACT_ROLES, suggestedRenewalSalary } from "../contracts/contractEngine.js";
import { ensurePlayerMorale, getMoraleLevel } from "../morale/moraleEngine.js";

export const COUNTRY_NAMES = { ES:"España", FR:"Francia", GH:"Ghana", BR:"Brasil", AR:"Argentina", PT:"Portugal", DE:"Alemania", ENG:"Inglaterra", UY:"Uruguay", HR:"Croacia", MA:"Marruecos", SN:"Senegal", BE:"Bélgica", IT:"Italia", NL:"Países Bajos" };
export const FLAGS = { ES:"🇪🇸", FR:"🇫🇷", GH:"🇬🇭", BR:"🇧🇷", AR:"🇦🇷", PT:"🇵🇹", DE:"🇩🇪", ENG:"🏴", UY:"🇺🇾", HR:"🇭🇷", MA:"🇲🇦", SN:"🇸🇳", BE:"🇧🇪", IT:"🇮🇹", NL:"🇳🇱" };
const fmtMoney = value => value >= 1000 ? `€${(value/1000).toFixed(value%1000===0?0:1)}M` : `€${value}K`;

function Metric({ label, value, color="#e8eaf0", helper }) {
  return <div style={{ background:"#161a24", border:"1px solid rgba(255,255,255,.06)", borderRadius:9, padding:11 }}><div style={{ fontSize:9, color:"#6b7280", fontWeight:700, letterSpacing:".4px" }}>{label}</div><div style={{ fontSize:19, color, fontWeight:800, marginTop:3 }}>{value}</div>{helper&&<div style={{ fontSize:9, color:"#4b5563", marginTop:2 }}>{helper}</div>}</div>;
}

function StatBar({ label, value }) {
  const color = value >= 85 ? "#c9a84c" : value >= 75 ? "#22c55e" : value >= 65 ? "#f59e0b" : "#ef4444";
  return <div style={{ marginBottom:12 }}><div style={{ display:"flex", justifyContent:"space-between", fontSize:11, marginBottom:5 }}><span style={{ color:"#9aa0b4" }}>{label}</span><strong style={{ color }}>{value}</strong></div><div style={{ height:5, background:"#252a36", borderRadius:4, overflow:"hidden" }}><div style={{ width:`${value}%`, height:"100%", background:color }}/></div></div>;
}

export default function PlayerProfileScreen({ player, game, team, onGoLineup, onGoTraining, onMarketStatus, onRenewalOffer, onGoContracts }) {
  player = ensurePlayerMorale(player, game.season);
  const [tab, setTab] = useState("general");
  const [statsSeason,setStatsSeason]=useState(String(game.season));
  const [renewSalary,setRenewSalary]=useState(suggestedRenewalSalary(player));
  const [renewYears,setRenewYears]=useState(player.age>=31?2:3);
  const [renewRole,setRenewRole]=useState(player.squadRole??"Rotación");
  const stats = useMemo(() => getPlayerSeasonStats(player, game, team?.id), [player, game, team?.id]);
  const form = useMemo(() => getRecentForm(player, game, team?.id), [player, game, team?.id]);
  const potential = getPotential(player);
  const marketValue = getMarketValue(player);
  const tags = getPlayerTags(player, stats, form, game.season);
  const attributes = getKeyAttributes(player);
  const relatedNews = (game.news ?? []).filter(item => item.playerIds?.includes(player.id));
  const history = player.careerHistory ?? [];
  const statsSeasons=[String(game.season),...history.map(entry=>String(entry.season)).filter((season,index,array)=>array.indexOf(season)===index&&season!==String(game.season))];
  const displayedStats=statsSeason===String(game.season)?stats:history.find(entry=>String(entry.season)===statsSeason)??{};
  const energy = Math.max(0, Math.round(100 - (player.fatigue ?? 0)));
  const accumulatedLoad = getAccumulatedLoad(player);
  const loadLevel = getLoadLevel(accumulatedLoad);
  const moraleLevel = getMoraleLevel(player.morale);
  const physicalStatus = getPhysicalStatus(player);
  const injuryRisk = calculateInjuryRisk(player,{fixtures:game.fixtures,teamId:team?.id,game});
  const injuryRiskLevel = getRiskLevel(injuryRisk);
  const isOwnPlayer = game.players.some(item => item.id === player.id);
  const activeRenewal=(game.contracts?.renewals??[]).find(item=>item.playerId===player.id&&!["completed","withdrawn"].includes(item.status));
  const isAcademyPlayer = player.academyStatus==="academy";
  const trainingReport = (isAcademyPlayer?game.lastYouthTrainingReport:game.lastTrainingReport)?.changes?.find(item=>item.playerId===player.id);
  const tabs = [["general","General"],["stats","Estadísticas"],["development","Desarrollo"],["contract","Contrato"],["history","Historial"],["news","Noticias"]];

  return <div style={{ flex:1, overflowY:"auto", background:"#0d0f14" }}>
    <section style={{ position:"relative", minHeight:218, overflow:"hidden", background:`linear-gradient(135deg,${team?.color ?? "#c9a84c"}33,#151925 55%,#0d0f14)` }}>
      <img src={player.imageUrl || `/players/${player.id}.png`} alt={player.name} onError={event=>event.currentTarget.style.display="none"} style={{ position:"absolute", right:-5, bottom:0, width:"52%", height:"95%", objectFit:"contain", objectPosition:"bottom" }}/>
      <div style={{ position:"absolute", inset:0, background:"linear-gradient(90deg,rgba(13,15,20,.98) 0%,rgba(13,15,20,.72) 55%,rgba(13,15,20,.12) 100%)" }}/>
      <div style={{ position:"relative", zIndex:1, padding:"22px 16px", maxWidth:"66%" }}>
        <div style={{ color:team?.color ?? "#c9a84c", fontSize:10, fontWeight:800, letterSpacing:".8px" }}>{team?.name ?? "Agente libre"}</div>
        <h1 style={{ fontSize:25, lineHeight:1.05, margin:"8px 0 9px", color:"#fff" }}>{player.name}</h1>
        <div style={{ fontSize:12, color:"#aab0bd", lineHeight:1.7 }}>{player.pos} · {player.age} años<br/>{FLAGS[player.nat] ?? "🌍"} {COUNTRY_NAMES[player.nat] ?? player.nat ?? "Internacional"}</div>
        <div style={{ display:"flex", gap:9, alignItems:"flex-end", marginTop:13 }}><div><div style={{ fontSize:9, color:"#6b7280", fontWeight:700 }}>MEDIA</div><div style={{ fontSize:34, lineHeight:1, fontWeight:900, color:"#c9a84c" }}>{player.overall}</div></div><div style={{ height:35, width:1, background:"rgba(255,255,255,.12)" }}/><div><div style={{ fontSize:9, color:"#6b7280", fontWeight:700 }}>POTENCIAL</div><div style={{ fontSize:25, lineHeight:1, fontWeight:900, color:"#e8eaf0" }}>{potential}</div></div></div>
      </div>
    </section>

    <nav style={{ display:"flex", overflowX:"auto", background:"#13161f", borderBottom:"1px solid rgba(255,255,255,.07)", position:"sticky", top:0, zIndex:4 }}>
      {tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{ flex:"1 0 auto", background:"transparent", border:"none", borderBottom:tab===id?"2px solid #c9a84c":"2px solid transparent", color:tab===id?"#c9a84c":"#6b7280", fontSize:10, fontWeight:700, padding:"11px 9px", cursor:"pointer" }}>{label}</button>)}
    </nav>

    <SwipeTabs tabs={tabs.map(([id])=>id)} activeTab={tab} onChange={setTab}>
    <div style={{ padding:14 }}>
      {tab==="general"&&<>
        {tags.length>0&&<div style={{ display:"flex", gap:6, flexWrap:"wrap", marginBottom:12 }}>{tags.map(tag=><span key={tag.label} style={{ background:`${tag.color}18`, border:`1px solid ${tag.color}44`, color:tag.color, borderRadius:15, padding:"5px 9px", fontSize:10, fontWeight:700 }}>{tag.icon} {tag.label}</span>)}</div>}
        {player.academyData&&<div style={{background:"rgba(34,197,94,.08)",border:"1px solid rgba(34,197,94,.2)",borderRadius:9,padding:11,marginBottom:12}}><div style={{color:"#22c55e",fontSize:10,fontWeight:800}}>🌱 FORMADO EN LA CANTERA</div><div style={{color:"#9aa0b4",fontSize:10,lineHeight:1.5,marginTop:4}}>Ingreso: T. {player.academyData.joinedSeason}/{String(Number(player.academyData.joinedSeason)+1).slice(-2)} · {player.academyData.region}<br/>Debut: {player.academyData.debutSeason?`T. ${player.academyData.debutSeason} · J${player.academyData.debutMatchday}`:"Pendiente"}</div></div>}
        <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>ESTADO ACTUAL</div>
        <div style={{ display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:7, marginBottom:16 }}><Metric label="ENERGÍA" value={`${energy}%`} color={energy>=70?"#22c55e":energy>=45?"#f59e0b":"#ef4444"} helper="estado inmediato"/><Metric label="CARGA ACUMULADA" value={`${loadLevel.icon} ${loadLevel.label}`} color={loadLevel.color} helper={`${accumulatedLoad}% · últimas semanas`}/><Metric label="MORAL" value={player.morale ?? 75} color={(player.morale??75)>=70?"#22c55e":"#f59e0b"}/><Metric label="FORMA" value={form.label} color={form.color}/></div>
        <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>VESTUARIO</div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:7,marginBottom:16}}><Metric label="PERSONALIDAD" value={player.personality?.profileLabel??"Equilibrado"} color="#c9a84c"/><Metric label="MORAL" value={`${moraleLevel.icon} ${moraleLevel.label}`} color={moraleLevel.color}/><Metric label="FELICIDAD" value={player.happiness??70} color={(player.happiness??70)>=55?"#22c55e":"#f97316"} helper="tendencia lenta"/><Metric label="CONFIANZA" value={player.managerTrust??70} color={(player.managerTrust??70)>=55?"#60a5fa":"#ef4444"} helper="relación con manager"/></div>
        <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>CICLO DE VIDA</div>
        <div style={{ display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:7, marginBottom:16 }}><Metric label="NACIMIENTO" value={player.birthDate??"—"} helper="fecha base"/><Metric label="ETAPA" value={player.lifecycle?.developmentStage??"Pico"} color={(player.age??25)>=34?"#f97316":(player.age??25)<=23?"#22c55e":"#c9a84c"}/>{player.lifecycle?.retirementPlan&&<Metric label="RETIRADA" value="Última temporada" color="#ef4444"/>}</div>
        <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>ESTADO MÉDICO</div>
        <div style={{ background:"#161a24", border:`1px solid ${physicalStatus.color}33`, borderRadius:10, padding:12, marginBottom:16 }}><div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:12 }}><div><div style={{ color:physicalStatus.color, fontSize:13, fontWeight:800 }}>{physicalStatus.icon} {physicalStatus.label}</div>{player.medical?.type&&player.medical.phase!=="available"&&<div style={{ color:"#9aa0b4", fontSize:10, marginTop:4 }}>{player.medical.type} · {formatMedicalDuration(player.medical.remainingDays??0)} restante</div>}</div><div style={{ textAlign:"right" }}><div style={{ color:injuryRiskLevel.color, fontSize:14, fontWeight:800 }}>{injuryRisk}%</div><div style={{ color:injuryRiskLevel.color, fontSize:9 }}>RIESGO {injuryRiskLevel.label.toUpperCase()}</div></div></div>{player.medical?.phase&&player.medical.phase!=="available"&&<div style={{ marginTop:10 }}><div style={{ height:5, background:"#252a36", borderRadius:3, overflow:"hidden" }}><div style={{ width:`${player.medical.recovery??0}%`, height:"100%", background:physicalStatus.color }}/></div><div style={{ color:"#4b5563", fontSize:9, marginTop:4 }}>Recuperación {player.medical.recovery??0}% · regreso estimado J{player.medical.expectedReturnMatchday??"—"}</div></div>}</div>
        <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>ATRIBUTOS CLAVE</div>
        <div style={{ background:"#161a24", borderRadius:10, padding:13, marginBottom:16 }}>{attributes.map(([label,value])=><StatBar key={label} label={label} value={value??player.overall}/>)}</div>
        <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>EVOLUCIÓN DE TEMPORADA</div>
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:7 }}><Metric label="MEDIA" value={`${player.seasonStartOverall??player.overall} → ${player.overall}`} color={player.overall>(player.seasonStartOverall??player.overall)?"#22c55e":"#e8eaf0"}/><Metric label="VALOR" value={`${fmtMoney(player.seasonStartValue??marketValue)} → ${fmtMoney(marketValue)}`} color={marketValue>(player.seasonStartValue??marketValue)?"#22c55e":"#e8eaf0"}/><Metric label="GOLES" value={`0 → ${stats.goals}`}/><Metric label="ASISTENCIAS" value={`0 → ${stats.assists}`}/></div>
      </>}

      {tab==="stats"&&<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px" }}>TEMPORADA</div><select value={statsSeason} onChange={event=>setStatsSeason(event.target.value)} style={{background:"#161a24",border:"1px solid rgba(201,168,76,.25)",color:"#c9a84c",borderRadius:7,padding:"7px 9px",fontSize:10,fontWeight:800}}>{statsSeasons.map(season=><option key={season} value={season}>{season}/{String(Number(season)+1).slice(-2)}{season===String(game.season)?" · actual":""}</option>)}</select></div><div style={{ display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:8 }}>{[["PARTIDOS",displayedStats.appearances??0],["TITULARIDADES",displayedStats.starts??"—"],["MINUTOS",displayedStats.minutes??"—"],["GOLES",displayedStats.goals??0],["ASISTENCIAS",displayedStats.assists??0],[(player.group==="POR"||player.pos==="POR")?"PORTERÍAS A CERO":"TARJETAS",(player.group==="POR"||player.pos==="POR")?(displayedStats.cleanSheets??"—"):`${displayedStats.yellows??0} 🟨 · ${displayedStats.reds??0} 🟥`],["NOTA MEDIA",displayedStats.averageRating??displayedStats.overall??"—"]].map(([label,value])=><Metric key={label} label={label} value={value}/>)}</div><div style={{ color:"#4b5563", fontSize:9, lineHeight:1.5, marginTop:12 }}>Los minutos y titularidades son exactos para los partidos registrados con el nuevo sistema. En temporadas antiguas pueden mostrarse estimaciones.</div></>}

      {tab==="development"&&<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:15}}><Metric label="MEDIA / POTENCIAL" value={`${player.overall} / ${potential}`} color="#c9a84c"/><Metric label="OBJETIVO ACTUAL" value={player.trainingFocus?ATTRIBUTE_LABELS[player.trainingFocus]:"General"}/></div><div style={{fontSize:10,color:"#6b7280",fontWeight:800,letterSpacing:".6px",marginBottom:8}}>PROGRESO DE ATRIBUTOS</div><div style={{background:"#161a24",borderRadius:9,padding:12,marginBottom:15}}>{Object.entries(player.developmentXP??{}).filter(([key])=>key!=="tactical").sort((a,b)=>b[1]-a[1]).slice(0,6).map(([key,value])=><div key={key} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",fontSize:10,marginBottom:4}}><span style={{color:"#9aa0b4"}}>{ATTRIBUTE_LABELS[key]??key}</span><span style={{color:"#c9a84c"}}>{Math.round(value)}%</span></div><div style={{height:5,background:"#252a36",borderRadius:3,overflow:"hidden"}}><div style={{width:`${Math.min(100,value)}%`,height:"100%",background:"#c9a84c"}}/></div></div>)}{!Object.keys(player.developmentXP??{}).length&&<div style={{color:"#6b7280",fontSize:11,textAlign:"center",padding:12}}>El progreso aparecerá tras el primer entrenamiento semanal.</div>}</div><div style={{fontSize:10,color:"#6b7280",fontWeight:800,letterSpacing:".6px",marginBottom:8}}>ÚLTIMO ENTRENAMIENTO</div><div style={{background:"#161a24",borderRadius:9,padding:12,color:trainingReport?.changes?.length?"#22c55e":"#9aa0b4",fontSize:11,lineHeight:1.5,marginBottom:15}}>{trainingReport?.changes?.length?trainingReport.changes.map(change=>`${change.label} ${change.delta>0?"+":""}${change.delta}`).join(" · "):trainingReport?.progress?.[0]?`${trainingReport.progress[0].label}: ${trainingReport.progress[0].value}% hacia la siguiente mejora.`:"Sin informe disponible todavía."}</div><div style={{fontSize:10,color:"#6b7280",fontWeight:800,letterSpacing:".6px",marginBottom:8}}>HISTORIAL DE DESARROLLO</div>{player.developmentHistory?.length?<div style={{display:"flex",flexDirection:"column",gap:7}}>{[...player.developmentHistory].reverse().map(entry=><div key={entry.season} style={{background:"#161a24",borderRadius:8,padding:10,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{color:"#c9a84c",fontSize:11,fontWeight:700}}>{entry.season}/{String(Number(entry.season)+1).slice(-2)}</div><div style={{color:"#6b7280",fontSize:9,marginTop:2}}>Valor: {fmtMoney(entry.startValue)} → {fmtMoney(entry.endValue)}</div></div><div style={{color:entry.endOverall>entry.startOverall?"#22c55e":"#e8eaf0",fontSize:13,fontWeight:800}}>{entry.startOverall} → {entry.endOverall}</div></div>)}</div>:<div style={{color:"#6b7280",fontSize:11}}>El historial se guardará al terminar la temporada.</div>}</>}

      {tab==="contract"&&<><div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:8 }}><Metric label="SALARIO" value={`€${player.salary??16}K`} helper="por semana"/><Metric label="CONTRATO" value={player.contractEnd??"—"} helper="año de finalización"/><Metric label="ROL" value={player.squadRole??"Rotación"}/><Metric label="CLÁUSULA" value={fmtMoney(player.releaseClause??Math.round(marketValue*1.7))}/><Metric label="VALOR DE MERCADO" value={fmtMoney(marketValue)}/><Metric label="ESTADO" value={Number(player.contractEnd??9999)<=Number(game.season)+1?"Último año":"Estable"} color={Number(player.contractEnd??9999)<=Number(game.season)+1?"#f59e0b":"#22c55e"}/></div>{activeRenewal?<div style={{background:"#161a24",border:"1px solid rgba(96,165,250,.22)",borderRadius:10,padding:12,marginTop:12}}><div style={{fontSize:10,color:"#60a5fa",fontWeight:900}}>NEGOCIACIÓN ACTIVA</div><div style={{fontSize:12,color:"#e8eaf0",marginTop:5}}>{activeRenewal.status}</div><div style={{fontSize:10,color:"#8b92a3",marginTop:5}}>Oferta: €{activeRenewal.salary}K/sem · {activeRenewal.years} años · {activeRenewal.role}</div><button onClick={onGoContracts} className="btn-gold" style={{width:"100%",marginTop:10,padding:9,borderRadius:8,fontSize:11}}>Abrir Contratos</button></div>:isOwnPlayer?<div style={{background:"#161a24",border:"1px solid rgba(201,168,76,.22)",borderRadius:10,padding:12,marginTop:12}}><div style={{fontSize:10,color:"#c9a84c",fontWeight:900,marginBottom:8}}>PROPONER RENOVACIÓN</div><div style={{display:"grid",gridTemplateColumns:"1fr 82px",gap:7}}><input type="number" value={renewSalary} onChange={event=>setRenewSalary(Number(event.target.value))} style={{background:"#1e2330",border:"1px solid rgba(255,255,255,.1)",color:"#fff",borderRadius:8,padding:9}}/><select value={renewYears} onChange={event=>setRenewYears(Number(event.target.value))} style={{background:"#1e2330",color:"#fff",border:"1px solid rgba(255,255,255,.1)",borderRadius:8}}>{[1,2,3,4,5].map(year=><option key={year} value={year}>{year} años</option>)}</select><select value={renewRole} onChange={event=>setRenewRole(event.target.value)} style={{gridColumn:"1 / -1",background:"#1e2330",color:"#fff",border:"1px solid rgba(255,255,255,.1)",borderRadius:8,padding:9}}>{CONTRACT_ROLES.map(role=><option key={role}>{role}</option>)}</select><button onClick={()=>onRenewalOffer?.(player.id,renewSalary,renewYears,renewRole)} className="btn-gold" style={{gridColumn:"1 / -1",padding:10,borderRadius:8}}>Enviar propuesta</button></div><div style={{fontSize:9,color:"#6b7280",lineHeight:1.4,marginTop:8}}>El jugador responderá en los próximos días. Puede aceptar, rechazar o pedir mejores condiciones.</div></div>:<div style={{ background:"rgba(201,168,76,.08)", border:"1px solid rgba(201,168,76,.2)", borderRadius:9, padding:12, color:"#9aa0b4", fontSize:11, lineHeight:1.5, marginTop:12 }}>Solo puedes renovar jugadores de tu plantilla.</div>}</>}

      {tab==="history"&&<><div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", marginBottom:8 }}>HISTORIAL DE TEMPORADAS</div>{history.length?<div style={{ display:"flex", flexDirection:"column", gap:8 }}>{history.map(entry=><div key={`${entry.season}-${entry.clubId}`} style={{ background:"#161a24", borderRadius:9, padding:12 }}><div style={{ color:"#c9a84c", fontWeight:800, fontSize:13 }}>{entry.season}/{String(Number(entry.season)+1).slice(-2)}</div><div style={{ color:"#9aa0b4", fontSize:11, margin:"3px 0 9px" }}>{entry.clubName}</div><div style={{ display:"flex", gap:16, fontSize:11, color:"#e8eaf0" }}><span>PJ: {entry.appearances}</span><span>G: {entry.goals}</span><span>A: {entry.assists}</span><span>Media: {entry.overall}</span></div></div>)}</div>:<div style={{ textAlign:"center", color:"#6b7280", padding:"20px 10px", fontSize:12 }}>El historial se completará al terminar la primera temporada.</div>}<div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", margin:"20px 0 8px" }}>HISTORIAL MÉDICO</div>{player.medicalHistory?.length?<div style={{ display:"flex", flexDirection:"column", gap:7 }}>{[...player.medicalHistory].reverse().map(item=><div key={item.id} style={{ background:"#161a24", borderLeft:"3px solid #f97316", borderRadius:8, padding:10 }}><div style={{ color:"#e8eaf0", fontSize:12, fontWeight:700 }}>{item.type}</div><div style={{ color:"#6b7280", fontSize:10, marginTop:3 }}>T. {item.season}/{String(Number(item.season)+1).slice(-2)} · J{item.matchday} · {item.totalDays} días</div></div>)}</div>:<div style={{ color:"#6b7280", fontSize:11 }}>No constan lesiones en su historial.</div>}</>}

      {tab==="news"&&(relatedNews.length?<div style={{ display:"flex", flexDirection:"column", gap:8 }}>{relatedNews.map(item=><div key={item.id} style={{ background:"#161a24", borderLeft:"3px solid #c9a84c", borderRadius:8, padding:11 }}><div style={{ color:"#e8eaf0", fontSize:12, fontWeight:700, lineHeight:1.4 }}>📰 {item.title}</div><div style={{ color:"#4b5563", fontSize:9, marginTop:5 }}>T. {item.seasonLabel}{item.matchday?` · J${item.matchday}`:""}</div></div>)}</div>:<div style={{ textAlign:"center", color:"#6b7280", padding:"35px 10px", fontSize:12 }}>Todavía no hay noticias relacionadas con este jugador.</div>)}

      <div style={{ fontSize:10, color:"#6b7280", fontWeight:800, letterSpacing:".6px", margin:"20px 0 8px" }}>ACCIONES RÁPIDAS</div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:7 }}><button onClick={()=>setTab("contract")} className="btn-gold" style={{ padding:10, borderRadius:8, fontSize:11 }}>📋 Ver contrato</button>{isOwnPlayer&&<button onClick={onGoLineup} style={{ background:"#1e2330", border:"1px solid rgba(255,255,255,.1)", color:"#e8eaf0", borderRadius:8, fontSize:11, cursor:"pointer" }}>🔄 Hacer titular</button>}{(isOwnPlayer||isAcademyPlayer)&&<button onClick={onGoTraining} style={{ background:"#1e2330", border:"1px solid rgba(255,255,255,.1)", color:"#e8eaf0", borderRadius:8, padding:10, fontSize:11, cursor:"pointer" }}>🏋 Entrenar</button>}{isOwnPlayer&&<button onClick={()=>onMarketStatus?.(player.id,"transfer")} style={{background:player.marketStatus==="transfer"?"#f59e0b":"rgba(245,158,11,.08)",border:"1px solid rgba(245,158,11,.25)",color:player.marketStatus==="transfer"?"#1a1200":"#f59e0b",borderRadius:8,padding:10,fontSize:10,fontWeight:800}}>{player.marketStatus==="transfer"?"Quitar transferible":"📌 Poner transferible"}</button>}{isOwnPlayer&&<button onClick={()=>onMarketStatus?.(player.id,"loan")} style={{background:player.marketStatus==="loan"?"#60a5fa":"rgba(96,165,250,.08)",border:"1px solid rgba(96,165,250,.25)",color:player.marketStatus==="loan"?"#08111f":"#60a5fa",borderRadius:8,padding:10,fontSize:10,fontWeight:800}}>{player.marketStatus==="loan"?"Quitar cedible":"🔁 Poner cedible"}</button>}</div>
    </div>
    </SwipeTabs>
  </div>;
}
