import { useMemo, useState } from "react";
import { getSquadNeeds, SCOUT_SPECIALTIES } from "../scouting/scoutingEngine.js";
import { SwipeTabs } from "./SwipeNavigation.jsx";

const gold="#c9a84c",panel="#161a24",muted="#6f7688";
const money=value=>`€${value>=1000?`${(value/1000).toFixed(1)}M`:`${Math.round(value)}K`}`;
function Title({children}){return <div style={{fontSize:9,color:muted,fontWeight:900,letterSpacing:".8px",margin:"17px 1px 8px"}}>{children}</div>}
function Empty({children}){return <div style={{background:panel,borderRadius:11,padding:24,textAlign:"center",fontSize:11,color:muted,lineHeight:1.6}}>{children}</div>}
function Meter({value,color=gold}){return <div style={{height:4,background:"#252a36",borderRadius:4,overflow:"hidden"}}><div style={{height:"100%",width:`${value}%`,background:color,transition:"width .3s"}}/></div>}

function ReportCard({report,watched,onWatch,onOpen}){
  return <div style={{background:`linear-gradient(145deg,${report.talent?.color??gold}0d,#161a24 55%)`,border:`1px solid ${report.talent?.color??gold}25`,borderRadius:12,padding:12,marginBottom:8}}><div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={()=>report.confidence>=88&&onOpen(report.player,report.teamId)} style={{width:43,height:43,borderRadius:10,border:"none",background:"rgba(201,168,76,.12)",color:gold,fontSize:13,fontWeight:900,cursor:report.confidence>=88?"pointer":"default"}}>{report.player.pos}</button><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,color:"#edf0f6",fontWeight:850,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{report.player.name}</div><div style={{fontSize:9,color:muted,marginTop:3}}>{report.player.age} años · {report.teamName} · {report.scoutName}</div>{report.talent&&<div style={{fontSize:9,color:report.talent.color,marginTop:3}}>{report.talent.icon} {report.talent.label}</div>}</div><button onClick={()=>onWatch(report.id)} style={{width:33,height:33,borderRadius:8,border:`1px solid ${watched?gold:"rgba(255,255,255,.08)"}`,background:watched?"rgba(201,168,76,.14)":"#1e2330",color:watched?gold:muted,cursor:"pointer"}}>{watched?"★":"👁"}</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6,marginTop:11}}>{[["MEDIA",`${report.overallRange[0]}-${report.overallRange[1]}`],["POTENCIAL",`${report.potentialRange[0]}-${report.potentialRange[1]}`],["CONFIANZA",`${report.confidence}%`]].map(([label,value])=><div key={label} style={{background:"rgba(5,8,12,.34)",borderRadius:7,padding:8,textAlign:"center"}}><div style={{fontSize:13,color:label==="POTENCIAL"?gold:"#d9dde7",fontWeight:900}}>{value}</div><div style={{fontSize:7,color:muted,marginTop:3}}>{label}</div></div>)}</div><div style={{marginTop:9}}><Meter value={report.confidence} color={report.confidence>=80?"#22c55e":report.confidence>=60?gold:"#f59e0b"}/></div>{report.opportunity&&<div style={{marginTop:8,background:"rgba(34,197,94,.09)",borderRadius:6,padding:6,color:"#22c55e",fontSize:9}}>💰 {report.opportunity}</div>}{report.confidence<88&&<div style={{fontSize:8,color:"#4f5565",marginTop:7}}>El perfil completo se desbloquea con un informe de confianza alta.</div>}</div>;
}

function Hub({game,onGoMarket}){
  const scouting=game.scouting;const needs=getSquadNeeds(game);const recommendations=scouting.reports.filter(item=>scouting.recommendations.includes(item.id));
  const ownProspect=[...(game.youth?.players??[])].sort((a,b)=>(b.potential??0)-(a.potential??0))[0];const external=[...scouting.reports].sort((a,b)=>b.potentialRange[1]-a.potentialRange[1])[0];
  return <><div style={{background:"radial-gradient(circle at 85% 0%,rgba(59,130,246,.24),transparent 38%),linear-gradient(145deg,#172033,#10131a)",border:"1px solid rgba(96,165,250,.22)",borderRadius:15,padding:16}}><div style={{fontSize:9,color:"#60a5fa",fontWeight:900,letterSpacing:"1.2px"}}>RED DE OBSERVACIÓN</div><div style={{fontSize:21,color:"#fff",fontWeight:900,marginTop:5}}>Informe del director deportivo</div><div style={{fontSize:11,color:"#9aa0b4",lineHeight:1.55,marginTop:6}}>{scouting.reports.length} jugadores analizados · {scouting.watchlist.length} en seguimiento · {scouting.missions.filter(item=>item.status==="active").length} misiones activas.</div><button onClick={onGoMarket} className="btn-gold" style={{width:"100%",borderRadius:8,padding:9,marginTop:13,fontSize:10}}>Abrir mercado analizado →</button></div>
    <Title>NECESIDADES DE PLANTILLA</Title><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}>{needs.map(item=><div key={item.group} style={{background:panel,borderLeft:`3px solid ${item.level==="Alta"?"#ef4444":item.level==="Media"?"#f59e0b":"#22c55e"}`,borderRadius:9,padding:10}}><div style={{fontSize:10,color:"#e8eaf0",fontWeight:800}}>{item.label}</div><div style={{fontSize:9,color:muted,marginTop:4}}>{item.count}/{item.target} jugadores · Media {item.quality}</div><div style={{fontSize:9,color:item.level==="Alta"?"#ef4444":item.level==="Media"?"#f59e0b":"#22c55e",marginTop:4}}>Necesidad {item.level.toLowerCase()}</div></div>)}</div>
    <Title>RECOMENDACIONES INICIALES</Title>{recommendations.length?<div style={{fontSize:10,color:"#9aa0b4",lineHeight:1.6,background:panel,borderRadius:10,padding:11}}>⭐ {recommendations.length} jugadores interesantes encontrados.<br/>💎 {recommendations.filter(item=>item.potentialRange[1]>=86).length} promesas de gran potencial.<br/>💰 {recommendations.filter(item=>item.opportunity).length} oportunidades de mercado.</div>:<Empty>El director deportivo todavía está preparando sus recomendaciones.</Empty>}
    <Title>CANTERA PROPIA VS TALENTO EXTERNO</Title><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}><div style={{background:panel,borderRadius:9,padding:11}}><div style={{fontSize:8,color:"#22c55e"}}>MEJOR CANTERANO</div><div style={{fontSize:11,color:"#fff",fontWeight:800,marginTop:5}}>{ownProspect?.name??"Sin datos"}</div><div style={{fontSize:9,color:muted,marginTop:3}}>Potencial {ownProspect?.potential??"—"}</div></div><div style={{background:panel,borderRadius:9,padding:11}}><div style={{fontSize:8,color:"#60a5fa"}}>PROMESA EXTERNA</div><div style={{fontSize:11,color:"#fff",fontWeight:800,marginTop:5}}>{external?.player.name??"Sin datos"}</div><div style={{fontSize:9,color:muted,marginTop:3}}>Potencial {external?`${external.potentialRange[0]}-${external.potentialRange[1]}`:"—"}</div></div></div></>;
}

function Missions({game,onStart}){
  const [form,setForm]=useState({group:"DEL",maxAge:"23",durationDays:"7",scoutId:game.scouting.scouts[0]?.id??"",region:"España"});const activeScoutIds=new Set(game.scouting.missions.filter(item=>item.status==="active").map(item=>item.scoutId));
  const submit=()=>onStart({...form,label:`Buscar ${form.group==="POR"?"portero":form.group==="DEF"?"defensa":form.group==="MED"?"centrocampista":"delantero"}${form.maxAge?` menor de ${Number(form.maxAge)+1} años`:""}`});
  return <><div style={{background:panel,borderRadius:12,padding:12}}><div style={{fontSize:11,color:"#fff",fontWeight:850,marginBottom:10}}>Nueva misión</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}><select value={form.group} onChange={e=>setForm({...form,group:e.target.value})} style={selectStyle}>{[["POR","Portero"],["DEF","Defensa"],["MED","Centrocampista"],["DEL","Delantero"]].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={form.maxAge} onChange={e=>setForm({...form,maxAge:e.target.value})} style={selectStyle}><option value="">Cualquier edad</option><option value="19">Sub-20</option><option value="23">Sub-24</option><option value="29">Hasta 29</option></select><select value={form.durationDays} onChange={e=>setForm({...form,durationDays:e.target.value})} style={selectStyle}>{[3,7,14,21].map(value=><option key={value} value={value}>{value} días</option>)}</select><select value={form.scoutId} onChange={e=>setForm({...form,scoutId:e.target.value})} style={selectStyle}>{game.scouting.scouts.map(item=><option disabled={activeScoutIds.has(item.id)} key={item.id} value={item.id}>{item.name} · Nv.{item.level}</option>)}</select></div><select value={form.region} onChange={e=>setForm({...form,region:e.target.value})} style={{...selectStyle,width:"100%",marginTop:7}}><option>España</option><option>Europa</option><option>Sudamérica</option><option>Internacional</option></select><button onClick={submit} className="btn-gold" style={{width:"100%",borderRadius:8,padding:9,marginTop:9,fontSize:10}}>🔎 Iniciar búsqueda</button></div>
    <Title>MISIONES</Title>{game.scouting.missions.length?<div style={{display:"flex",flexDirection:"column",gap:7}}>{game.scouting.missions.map(item=><div key={item.id} style={{background:panel,borderRadius:10,padding:11}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><div><div style={{fontSize:11,color:"#e8eaf0",fontWeight:800}}>{item.label}</div><div style={{fontSize:9,color:muted,marginTop:3}}>{item.scoutName} · {item.region} · {item.durationDays} días</div></div><span style={{fontSize:9,color:item.status==="completed"?"#22c55e":gold}}>{item.status==="completed"?"COMPLETADA":`${item.progress}%`}</span></div><div style={{marginTop:9}}><Meter value={item.progress} color={item.status==="completed"?"#22c55e":gold}/></div></div>)}</div>:<Empty>Crea una búsqueda. El informe llegará tras disputar las jornadas necesarias.</Empty>}</>;
}
const selectStyle={background:"#1e2330",border:"1px solid rgba(255,255,255,.09)",color:"#dce0e8",borderRadius:7,padding:8,fontSize:10,minWidth:0};

function Network({game}){return <><div style={{background:"linear-gradient(135deg,rgba(59,130,246,.14),#161a24)",border:"1px solid rgba(59,130,246,.2)",borderRadius:12,padding:13,fontSize:10,color:"#9aa0b4",lineHeight:1.55}}>El prestigio del club amplía la red, mejora la precisión y permite atraer ojeadores de mayor nivel.</div><Title>CUERPO DE OJEADORES</Title>{game.scouting.scouts.map(item=>{const specialty=SCOUT_SPECIALTIES[item.specialty];const active=game.scouting.missions.find(mission=>mission.scoutId===item.id&&mission.status==="active");return <div key={item.id} style={{background:panel,borderRadius:11,padding:12,marginBottom:8,display:"flex",gap:11,alignItems:"center"}}><div style={{width:42,height:42,borderRadius:11,display:"grid",placeItems:"center",fontSize:20,background:"rgba(96,165,250,.1)"}}>{specialty?.icon}</div><div style={{flex:1}}><div style={{fontSize:12,color:"#fff",fontWeight:850}}>{item.name}</div><div style={{fontSize:9,color:"#60a5fa",marginTop:3}}>{specialty?.label} · Nivel {item.level}</div><div style={{fontSize:9,color:active?gold:muted,marginTop:3}}>{active?`🔎 ${active.label}`:"Disponible"}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:16,color:gold,fontWeight:900}}>{item.experience}%</div><div style={{fontSize:7,color:muted}}>EXPERIENCIA</div></div></div>})}</>}

export default function ScoutingScreen({game,onStartMission,onToggleWatch,onOpenPlayer,onGoMarket}){
  const [tab,setTab]=useState("hub");const tabs=[["hub","Red"],["missions","Misiones"],["reports","Informes"],["watch","Seguimiento"],["network","Ojeadores"]];const watched=new Set(game.scouting.watchlist);const reports=game.scouting.reports;const watchReports=reports.filter(item=>watched.has(item.id));
  return <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}><div style={{display:"flex",overflowX:"auto",background:"#141821",borderBottom:"1px solid rgba(255,255,255,.06)"}}>{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{flex:"1 0 80px",background:"transparent",border:"none",borderBottom:tab===id?`2px solid ${gold}`:"2px solid transparent",color:tab===id?gold:muted,padding:10,fontSize:10,fontWeight:800}}>{label}</button>)}</div><SwipeTabs tabs={tabs.map(item=>item[0])} activeTab={tab} onChange={setTab} style={{flex:1,display:"flex",overflow:"hidden"}} contentStyle={{flex:1,overflow:"hidden"}}><div style={{height:"100%",overflowY:"auto",padding:14}}>{tab==="hub"&&<Hub game={game} onGoMarket={onGoMarket}/>} {tab==="missions"&&<Missions game={game} onStart={onStartMission}/>} {tab==="reports"&&(reports.length?reports.map(item=><ReportCard key={item.id} report={item} watched={watched.has(item.id)} onWatch={onToggleWatch} onOpen={onOpenPlayer}/>):<Empty>No hay informes disponibles.</Empty>)} {tab==="watch"&&(watchReports.length?watchReports.map(item=><ReportCard key={item.id} report={item} watched onWatch={onToggleWatch} onOpen={onOpenPlayer}/>):<Empty>Marca jugadores con 👁 para recibir seguimiento continuo.</Empty>)} {tab==="network"&&<Network game={game}/>}</div></SwipeTabs></div>;
}
